version: "3"

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: persons_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: person-server
    image: app
    build:
      context: .
      dockerfile:  dockerfile
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      database:
        condition: service_healthy
volumes:
  data:
    driver: local

networks:
  default: